matrix:
  include:
  - language: bash
    os: linux
    dist: precise
    sudo: required
    install:
    - "./install.sh"
    script:
    - "./build.sh"
    - "./tests/test-custom-check.sh"
  - language: bash
    os: linux
    dist: trusty
    sudo: required
    install:
    - "./install.sh"
    script:
    - "./build.sh"
    - "./tests/test-custom-check.sh"
  - language: bash
    os: osx
    dist: precise
    sudo: required
    install:
    - "./install.sh"
    script:
    - "./build.sh"
    - "./tests/test-custom-check.sh"
  - language: ruby
    rvm: 2.2
    before_script: gem install awesome_bot
    script: find . -type f -name "*.md" | while read file; do awesome_bot $file --allow-redirect
      --allow-dupe -w github.com/TravisToolbox/shellcheck-travis/issues/; done
notifications:
  email: false
  slack:
    secure: gU/AWnWgZdd2X0sZd2InyGv+sdQ1yFKbtEdtkBYTFJO7zMdFChiPDJY0K9oi5+JdanlcoWBvJAXZbD4bzhHR2BDvpEcCORckS/V4rDbeI9pzKchJSkh6JZ8FPSUxD+p+DbGBvc4Er4de72Htjyxs0FNfz//mP20OqyKnFE/tVv/JBg3CE5nl2tAB+yhj9lPx1gRq0m3d808jPwzjhix8sTgT8aoFEf57F3oQxrASDTD3vcj3Ts4pCVIu3Oze5CDuQBZYxbSdgbJdmFP+Vj/hQYNxC6FrRoG1NTAL1ZM+xS6Mdn/pKTkl+k7S1FWly0GNiYNDEskDkA6jhGiroIDrZoIZCJ1DN5uckIZlzabG6LD/hT1eHQ/L0b28rZPbLYJx/ibtm/w2dq3gfnpypbQs1o5L56l6/WcZQNnq2fR9uJYhuMwJdnjTymD7zX7p7r+CMdNFlCwT//z4l2lbLMVd/IS48Q0PHhLOYlcWLP3kKh5ivfZgQqh5iT1TzmR/zGrsbqcTpEfTKzbMUF6qyq8t4SkBzbDGHXTWL1rlo7WpfOywq9DCF2yzKWkcX1MPs8KakUm60kRxeJIudmbF6jBSddAa+fnbRp4A/xgMydlAnmyN/lduzwQGeD+rHBuBoGCkCv6kBQjRA1ucbNsOG2lmvrmkp7GUcU1HBW4+xIJszLU=
